apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-function-get-observed-resource-condition
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            status:
              # Only add status fields from composed resource when when said resource exists and is ready
              {{ if eq (getObservedResourceCondition . "project" "Ready").Status "True" }}
              projectId: {{ .observed.resources.project.resource.status.atProvider.id | quote }}
              {{ end }}
              fullCondition:
                {{ getObservedResourceCondition . "project" "Ready" | toYaml | nindent 17 }}
