apiVersion: identity.openstack.upbound.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    crossplane.io/composition-resource-name: project
  labels:
    crossplane.io/composite: myproject
  name: myproject
spec:
  forProvider:
    name: myproject
  providerConfigRef:
    name: myprovider
status:
  atProvider:
    id: abcdef
