# This composition expects to find the templates in filesystem.
# You can create a configmap and mount it using DeploymentRuntimeConfig.
# Please check the examples/functions.yaml file for an example.
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xusers.aws.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XUser
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: FileSystem
        fileSystem:
          dirPath: /templates
    - step: ready
      functionRef:
        name: function-auto-ready
