apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xusers.aws.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XUser
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: FileSystem
        fileSystem:
          dirPath: /templates
    - step: ready
      functionRef:
        name: function-auto-ready

---

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xusers.aws.platformref.upbound.io
spec:
  group: aws.platformref.upbound.io
  names:
    kind: XUser
    plural: xusers
  claimNames:
    kind: MyUser
    plural: myusers
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: ID of this user that other objects will use to refer to it.
                count:
                  type: integer
              required:
                - id
                - count