apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/ezgi/function-go-templating:v0.0.1  # TODO(ezgidemirel): Update package
  packagePullPolicy: Always
  # Please uncomment the following lines if you want to mount the templates from a config map with the following DeploymentRuntimeConfig resource.
#  runtimeConfigRef:
#    name: mount-templates

---

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: mount-templates
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              volumeMounts:
                - mountPath: /templates
                  name: templates
                  readOnly: true
          volumes:
            - name: templates
              configMap:
                name: templates

---

apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.1.0