apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-inline
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            conditions:
              - type: Progressing
                status: true
                reason: Testing
                message: Hello World
                target: composite
              - type: Walking
                status: unknown
              - type: Running
                status: "true"
                reason: StringValue
            results:
              - severity: normal
                reason: norway
                message: foo
                target: composite
            requirements:
              resources:
                ns:
                  apiVersion: v1
                  kind: Namespace
                  matchName: foo
                ns2:
                  apiVersion: v1
                  kind: Namespace
                  matchLabels:
                    labels:
                      foo: bar
                      fuz: buf
                ns3:
                  apiVersion: v1
                  kind: Namespace
                  matchLabels:
                    labels: {}
            desired:
              resources:
                sa:
                  resource:
                    apiVersion: v1
                    kind: ServiceAccount
                    metadata:
                      name: {{ .observed.composite.resource.metadata.name }}
                  ready: true
                {{- with .observed.resources.sa.resource }}
                cm:
                  resource:
                    apiVersion: v1
                    kind: ConfigMap
                    metadata:
                      name: foo
                    data:
                      serviceAccountName: {{ .metadata.name }}
                  ready: false
                {{- end }}
