apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    crossplane.io/composition-resource-name: sa
  labels:
    crossplane.io/composite: example
  name: example
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""

